### ISSUE TITLE
Provide credentials for base image different from the image to be built

### ISSUE THREAD

**Issue by chbiel** [concourse/docker-image-resource#277] opened 2019-08-22 07:11 UTC
Hi,
i have the following setup:

Dockerfile of "child" image
`FROM quay.io/team/base
...do something...`

quay.io need authentication and the following would work as expected.
`- name: docker-image-tools
    type: docker-image
    icon: docker
    source:
      repository: quay.io/team/base
      username: ((quay_username))
      password: ((quay_password))`

Now I want to build the "child" image above, but push it to AWS ECR:
`- name: docker-image-child
    type: docker-image
    icon: docker
    source:
      repository: account.dkr.ecr.region.amazonaws.com/child`

When I execute that I get an error that authentication for quay.io is missing (what is basically OK).

But now the question:
Can I provide different credentials for the base image and the image to created/push? Or do i have to ensure that the base image and the target image are in the same repo?

**Comment by vito** [comment] 2019-09-25 20:09
(dupe of https://github.com/concourse/docker-image-resource/issues/278)

**Closed by vito** 2019-09-25 20:09 UTC
