### ISSUE TITLE
Amazon ECR Support Proposal

### ISSUE THREAD

**Issue by eploko** [concourse/docker-image-resource#36] opened 2016-05-04 09:49 UTC
### The Scope of the Problem

I've been playing with Concourse for some time. As it turns out there's just a single thing that keeps me from bringing it into our CI process: I couldn't find a way to provide ECR credentials to the docker-image resource.

The problem lies in the fact that the ECR uses temporary tokens to provide access to repos. One would naïvely try to obtain the token manually and provide it to the resource as the password. But then the token expires in 12 hours and the pipeline fails to push the image. In this state the whole idea of Concourse as a CI system is kind of pointless, as one needs to update the credentials in the pipeline.yml file and then push the pipeline via fly each 12 hours.

### How This Could Be Improved Upon

When the `repository` param for the resource is set to an ECR repo like `XXXX.dkr.ecr.REGION.amazonaws.com/REPO_NAME`, the resource may treat the `username` and `password` fields as the AWS access and secret keys. It would then use these to fetch an ECR token from AWS and use that for further docker calls.

Do you think this would be an adequate strategy for tackling the problem?

I would be happy to try to implement this and make a PR if this all makes sense.

**Comment by smazurov** [comment] 2016-06-21 02:48
I'm evaluating Concourse now, and because we heavily use ECR, this is also an issue for us. Any chance the PR gets merged?

**Comment by farahfa** [comment] 2016-06-24 16:42
I got tired of waiting so, I've created a resource based on eploko's fix and it works just fine!

Here's my pipeline that includes this resource for reference.

```
resource_types:
- name: aws-ecr-docker-registry
  type: docker-image
  source:
    repository: covisintrnd/ecr-docker-image-resource

resources:
- name: nexus-docker-image
  type: aws-ecr-docker-registry
  source:
    username: {{aws_access_key_id}}
    password: {{aws_secret_access_key}}
    aws_region: {{ecr_region}}
    repository: {{ecr-nexus-repo}}
    tag: test
```

I'm running into a small issue where if push an image to ECR it pulls it after, not sure if it's something related to this or not, but it's something to be aware of.

**Comment by oppegard** [comment] 2016-06-27 19:10
@farahfa Concourse pulling the docker image after pulling is expected behavior.

How has this been working for you? Any comparisons to using ECR vs Docker Hub for speed and reliability? We have 1GB compressed images (2.6GB uncompressed) that take a fair bit of time to pull/push to Docker Hub. If ECR was faster, we may look at it as an option.

**Comment by farahfa** [comment] 2016-06-27 20:52
So the pulling docker after pushing was my fault (I forgot to add ```skip_download: true```).

And so far ECR has been working very well for us (but this is also because our VMs are on AWS), so everything has been going really fast for us. Hope this helps.

**Comment by jcderr** [comment] 2016-06-29 20:36
This is also the only issue preventing my adoption of Concourse.

I'd like to add that we do not provide AWS keys to our instances and instead use IAM instance profiles. If no username/password is provided, the code should still attempt to fetch credentials, as doing so will still succeed in this situation.

**Comment by nalindak** [comment] 2016-07-06 03:41
We are experimenting with ECS and ECR, our concourse workers running on ECS cluster. Can we achieve above like below,

- attach IAM role to worker container instance to retrieve login-credentails for the ECR
- Then run `aws ecr get-login --region $(ECR_REGION) | sh` to get credentials and execute login (here in the container needs to have `aws` command line installed)
- Then pull the instance images as usual

**Comment by oppegard** [comment] 2016-07-06 18:57
FYI, there's an [ECR Docker Credential Helper](https://github.com/awslabs/amazon-ecr-credential-helper) from AWS that integrates with the [Docker Credential Helpers](https://github.com/docker/docker-credential-helpers) plugin system. Adding support for credential plugins in this Concourse resource may be the way to go.

**Comment by kimeberz** [comment] 2016-07-08 00:37
Long-term, we would like https://github.com/hashicorp/vault/issues/1244 to happen so that we can just implement https://github.com/concourse/concourse/issues/291 and have all resources acquire credentials in one way.

Short-term, we're happy to merge a PR that just friggin uses ECR, since a bunch of people need it. Overloading `username` and `password` based on the format of the repository URI feels a little magical though - can we just add explicit fields for the AWS access key and secret key?

This PR seems close to that: https://github.com/concourse/docker-image-resource/pull/52 - we'll leave a comment on there directing it a bit more.

- @vito & @kimeberz

**Comment by jcderr** [comment] 2016-07-08 00:55
IAM instance profile users will not have any AWS access keys to provide.

I have no use for Vault here. I literally just need concourse to make an
API call to AWS and use the user/pass it gets back.
On Thu, Jul 7, 2016 at 7:37 PM Kimberly Eberz <notifications@github.com>
wrote:

> Long-term, we would like hashicorp/vault#1244
> <https://github.com/hashicorp/vault/issues/1244> to happen so that we can
> just implement concourse/concourse#291
> <https://github.com/concourse/concourse/issues/291> and have all
> resources acquire credentials in one way.
>
> Short-term, we're happy to merge a PR that just friggin uses ECR, since a
> bunch of people need it. Overloading username and password based on the
> format of the repository URI feels a little magical though - can we just
> add explicit fields for the AWS access key and secret key?
>
> This PR seems close to that: #52
> <https://github.com/concourse/docker-image-resource/pull/52> - we'll
> leave a comment on there directing it a bit more.
>
>    - @vito <https://github.com/vito> & @kimeberz
>    <https://github.com/kimeberz>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/concourse/docker-image-resource/issues/36#issuecomment-231246891>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAMoRm4A2GNa8DYkxbNzLuLXcDAEEg2cks5qTZu3gaJpZM4IW_KA>
> .
>
-- 
Jeremy Derr
jeremy@derr.me

When in trouble or in doubt, run in circles, scream and shout.

**Comment by vito** [comment] 2016-07-08 01:01
You may literally just need to make an API call to AWS. The next guy person literally just needs an API call to LastPass. The next person may need an API call to some other credential store. We can't have every single resource implement every single integration.

We're making an exception for this one - for now - as so many people have run into it, and Vault doesn't yet support ECR.

**Comment by jcderr** [comment] 2016-07-08 01:37
In this case, I wouldn't really think of it as supporting a credential
source like Lastpass, but more akin to providing the required native
support for one of the biggest docker clustering environments available.

It's probably within scope to consider (eventually) providing such support
for services/toolsets that are popular on the order of ECS, Mesos, and
Kubernetes.
On Thu, Jul 7, 2016 at 8:01 PM Alex Suraci <notifications@github.com> wrote:

> You may literally just need to make an API call to AWS. The next guy
> person literally just needs an API call to LastPass. The next person may
> need an API call to some other credential store. We can't have every single
> resource implement every single integration.
>
> We're making an exception for this one - for now - as so many people have
> run into it, and Vault doesn't yet support ECR.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/concourse/docker-image-resource/issues/36#issuecomment-231250122>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAMoRsWpM_p_AomJ5aogoTGJSamPzFOAks5qTaFdgaJpZM4IW_KA>
> .
>
-- 
Jeremy Derr
jeremy@derr.me

When in trouble or in doubt, run in circles, scream and shout.

**Comment by vito** [comment] 2016-07-08 01:59
The thing to understand is that with Concourse, resources are the single extension point, and there are or will be hundreds of them. If you multiply that by the number of integration points and credential services, that means hundreds of people responsible for implementing dozens of credential endpoints. This is why I'm strongly in favor of having resources stay as simple as possible: 100% self-contained JSON goes in, the script runs, and JSON comes out.

I'm not at all against ECR and don't doubt its importance or relevance to the Docker Image resource. I want to avoid setting a precedent for credential management with resources. We're making a special exception in this case because people need it. I don't know what more you want.

**Comment by vito** [comment] 2016-07-24 18:11
This should be in the next release.

**Comment by vito** [comment] 2016-07-25 04:28
This is proving to be unnecessarily difficult, as is my usual experience dealing with Docker APIs. 😞 

`in` and `out` work using the credential helper, but `check` hits the registry API directly, and ECR apparently does *NOT* conform to the API spec. It doesn't return the `Docker-Content-Digest` header, which we use to detect the current version of the image. (I also lost quite a few hours to a missing trailing slash in the auth flow, which works fine on other registries. Ugh.)

Given that this one (particularly important) piece of data is not available elsewhere in the API (annoying that they shove it in a header), we may be a bit stuck here.

**Comment by vito** [comment] 2016-07-25 04:53
Scratch that. Found the light at the end of the tunnel after some sleuthing through the distribution codebase, and we should be all set.

Another fun thing: ECR's registry API returns `404`, not `405` if you try to do a `HEAD` request against the manifest endpoint. If it returned `405` I could use shinier higher-level methods exposed by `distribution`. But it doesn't. Oh well.

**Closed** 2016-07-25 15:23 UTC
Labels: enhancement
